#!/bin/sh -e

MYDIR=$(dirname "$0")
PORT="$1"

cd "$MYDIR"

if [ -z "$PORT" ]; then
    echo "usage: $0 PORT" 1>&2
    echo "Choose port from list at http://punter.inf.ed.ac.uk/status.html" 1>&2
    exit 1
fi
export DUMP_STATE=$MYDIR/dumps/online-$PORT.dump
lamduct \
      --game-port "$PORT" \
      --client-instance-logfile "$MYDIR/logs/$PORT.log" \
      --log-level 3 \
      "./punter"
