#!/bin/sh -e

MYDIR=$(dirname "$0")
PORT="$1"

cd "$MYDIR"

if [ -z "$PORT" ]; then
    echo "usage: $0 PORT" 1>&2
    echo "Choose port from list at http://punter.inf.ed.ac.uk/status.html" 1>&2
    exit 1
fi

lamduct \
      --game-port "$PORT" \
      --client-instance-logfile "$MYDIR/logs/punt.log" \
      --log-level 1 \
      "./punter"
