#!/bin/sh -e

map=$1
players=$2

if [ -z "$players" ]; then
    echo "usage: $0 map-base-name num-players" 1>&2
    exit 1
fi

dumpfile="dumps/elm-vis-dump.js"

rm -f dumps/elm-vis-dump.js

stack build
time stack exec evolver "examples/$map.json" "$dumpfile" "$players"

open "visualiser/index.html"
