#!/bin/sh -e

map=$1
players=$2
dump_game_num=$3

if [ -z "$dump_game_num" ]; then
    echo "usage: $0 map-base-name player dump-game-num" 1>&2
    exit 1
fi

dumpfile="dumps/$map.dump"

stack build
time stack exec evolver "examples/$map.json" "$players" "$dump_game_num" "$dumpfile"

rm -rf visualisations
mkdir visualisations
stack exec visualise "$dumpfile"
open visualisations
