flags:
  time-locale-compat:
    old-locale: false
extra-package-dbs: []
packages:
- '.'
extra-deps:
- aeson-1.2.1.0
- attoparsec-0.13.2.0
- base-compat-0.9.3
- blaze-builder-0.4.0.2
- blaze-markup-0.8.0.0
- blaze-svg-0.3.6.1
- dlist-0.8.0.3
- integer-logarithms-1.0.2
- scientific-0.3.5.1
- tagged-0.8.5
- time-locale-compat-0.1.1.3
- transformers-compat-0.5.1.4
- uuid-types-1.0.3
resolver: ghc-8.0.1
